version: '3'
services:
  db:
    container_name: mysql_shortener
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - ./config.env
#    ports:         #for debug
#      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'urls'
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    networks:
      default:
        ipv4_address: 172.20.0.2

  cache:
    container_name: cache_shortener
    image: bitnami/redis:latest
    restart: unless-stopped
    env_file:
      - ./config.env
#    ports:         #for debug
#      - '6379:6379'
    networks:
      default:
        ipv4_address: 172.20.0.3

  shortener:
    container_name: shortener
    build: .
    restart: unless-stopped
    env_file:
      - ./config.env
    ports:
      - '8080:8080'
    networks:
      default:
        ipv4_address: 172.20.0.4
    environment:
      MYSQL_ADDRESS: '172.20.0.2:3306'
      REDIS_ADDRESS: '172.20.0.3:6379'
      MYSQL_DB: 'urls'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24